---
title: "Data Generation"
---

```{r}
library(ggplot2)
library(survival)
library(tidyverse)
library(knitr)
library(kableExtra)
```


```{r}
generate_data <- function(
  n = 2000,
  pA = 0.5,
  mu_X = c(60, 120),          # mean for each covariate
  sd_X = c(10, 15),           # sd for each covariate
  beta_X = c(0.03, 0.014),    # coefficients for covariates
  beta_A = 0,                 # group effect
  lambda = 0.004,             # baseline rate for Weibull
  k = 1.5,                    # shape parameter
  # mu,                   # baseline censoring rate
  b_c,
  p_c,
  alpha = 0,                  # censoring dependence
  Cmax_A0 = 10,               # max follow-up (group 0)
  Cmax_A1 = 10,               # max follow-up (group 1)
  seed = 497
) {
  set.seed(seed)
  
  pX <- length(mu_X)
  if (length(sd_X) != pX | length(beta_X) != pX)
    stop("Lengths of mu_X, sd_X, and beta_X doesn't match.")
  
  # Sensitive attribute
  A <- rbinom(n, 1, pA)
  
  # Covariates
  X <- matrix(NA, nrow = n, ncol = pX)
  for (j in 1:pX) {
    X[, j] <- rnorm(n, mean = mu_X[j], sd = sd_X[j])
  }
  colnames(X) <- c("age", "LOS", "eGFR", "Hemoglobin", "CCI")
  
  # True event time 
  Z <- scale(X, center = mu_X, scale = sd_X)
  eta <- as.vector(Z %*% beta_X) + beta_A * A
  
  # eta <- beta_A * A + X %*% beta_X
  U <- runif(n)
  T_true <- ((-log(U)) / (lambda * exp(eta)))^(1 / k)
  
  # Max follow-up
  Cmax <- ifelse(A == 0, Cmax_A0, Cmax_A1)
  
  #  Censoring time
  Uc <- runif(n)
  biased_Uc <- Uc^(exp(alpha * eta))
  C <- (biased_Uc)^(1 / p_c) * Cmax
  # C <- (biased_Uc)^(1 / p_c) * max(Cmax_A0, Cmax_A1)
  
  # Observed data
  Y <- pmin(T_true, C, Cmax)
  Delta <- as.numeric(T_true <= pmin(C, Cmax))
  
  data <- data.frame(
    id = 1:n,
    A = A,
    X,
    T_true = T_true,
    C = C,
    Cmax = Cmax,
    Y = Y,
    Delta = Delta
  )
  
  return(data)
}



```

```{r}
# Example

# X choice:
mu_X = c(50,    # age
         5,   # LOS (Length of Stay)
         70,    # eGFR
         13.2,  # Hemoglobin
         2)     # CCI (Charlson Comorbidity Index)
         

sd_X = c(15,    # age
         2.5,   # LOS (Length of Stay)
         20,    # eGFR
         1.6,  # Hemoglobin
         1.5)     # CCI (Charlson Comorbidity Index)

beta_X = c(0.3,  # age
         0.4,   # LOS (Length of Stay)
         -0.22,    # eGFR
         -0.3,  # Hemoglobin
         0.35)     # CCI (Charlson Comorbidity Index)

# beta_X = c(0.3,  # age
#          0.4,   # LOS (Length of Stay)
#          -0.25,    # eGFR
#          -0.3,  # Hemoglobin
#          0.4)     # CCI (Charlson Comorbidity Index)

k <- 3
lambda <- 1e-10

b_c <- 3000
p_c <- 3


# Scenario I: all assumptions hold
data_I <- generate_data(
  n = 8000,
  mu_X = mu_X,
  sd_X = sd_X,
  beta_X = beta_X,
  lambda = lambda,
  k = k,
  b_c = b_c,
  p_c = p_c,
  beta_A = 0,
  alpha = 0,
  Cmax_A0 =3000,
  Cmax_A1 = 3000
)
data_I <- data_I |> filter(age > 1, C > 1, LOS > 0.1, eGFR > 0.1, Hemoglobin > 0.1, CCI > 0.1)
data_I$CCI  <- round(data_I$CCI)

# Scenario II: violation of assumptions
data_II <- generate_data(
  n = 8000,
  mu_X = mu_X,
  sd_X = sd_X,
  beta_X = beta_X,
  lambda = lambda,
  k = k,
  b_c = b_c,
  p_c = p_c,
  beta_A = -0.5,
  alpha = 0.5,
  Cmax_A0 = 3000,
  Cmax_A1 = 3500
)

data_II <- data_II |> filter(age > 1, C > 1, LOS > 0.1, eGFR > 0.1, Hemoglobin > 0.1, CCI > 0.1)
data_II$CCI  <- round(data_II$CCI)


# head(data_I)
# head(data_II)


```

```{r}
dat <- data_I
# dat <- read.csv("data/data_I.csv")

cat("Dataset size:", nrow(dat), "\n")
cat("Columns:", names(dat), "\n")

summary(dat)

cat("\nOverall censoring rate:\n")
mean(dat$Delta == 0)

cat("\nCensoring rate by group (A=0, A=1):\n")
tapply(dat$Delta == 0, dat$A, mean)

summary(dat$C)

ggplot(dat, aes((x = C), fill = factor(A))) +
  geom_histogram(alpha = 0.5, bins = 50, position = "identity") +
  labs(
    title = "Non-informative Censoring Time C Distribution",
    x = "C",
    y = "Count"
  ) +
  theme_minimal()

ggplot(dat, aes(x = T_true)) +
  geom_histogram(bins = 40, fill = "skyblue", color = "white") +
  labs(title = "True Time Distribution",
       x = "True Time (T)",
       y = "Count")+
  theme_minimal()

ggplot(dat, aes(x = Y, fill = factor(A))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Observed Time Distribution by Group",
       x = "Observed Time (Y)",
       fill = "Group A") +
  theme_minimal()

ggplot(dat, aes(x = Y, fill = factor(Delta))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Events (Δ=1) vs Censored (Δ=0)",
       x = "Observed Time",
       fill = "Event Indicator") +
  theme_minimal()

ggplot(dat, aes(x = age, fill = factor(A))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Age Distribution by Group", fill = "Group A") +
  theme_minimal()

ggplot(dat, aes(x = LOS, fill = factor(A))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "LOS Distribution by Group", fill = "Group A") +
  theme_minimal()


```

```{r}
dat <- data_II

cat("Dataset size:", nrow(dat), "\n")
cat("Columns:", names(dat), "\n")

summary(dat)

cat("\nOverall censoring rate:\n")
mean(dat$Delta == 0)

cat("\nCensoring rate by group (A=0, A=1):\n")
tapply(dat$Delta == 0, dat$A, mean)

summary(dat$C)

ggplot(dat, aes((x = C), fill = factor(A))) +
  geom_histogram(alpha = 0.5, bins = 50, position = "identity") +
  labs(
    title = "Informative Censoring Time C Distribution",
    x = "C",
    y = "Count"
  ) +
  theme_minimal()

ggplot(dat, aes(x = T_true)) +
  geom_histogram(bins = 40, fill = "skyblue", color = "white") +
  labs(title = "True Time Distribution",
       x = "True Time (T)",
       y = "Count")+
  theme_minimal()

ggplot(dat, aes(x = Y, fill = factor(A))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Observed Time Distribution by Group",
       x = "Observed Time (Y)",
       fill = "Group A") +
  theme_minimal()

ggplot(dat, aes(x = Y, fill = factor(Delta))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Events (Δ=1) vs Censored (Δ=0)",
       x = "Observed Time",
       fill = "Event Indicator") +
  theme_minimal()

ggplot(dat, aes(x = age, fill = factor(A))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Age Distribution by Group", fill = "Group A") +
  theme_minimal()

ggplot(dat, aes(x = LOS, fill = factor(A))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "LOS Distribution by Group", fill = "Group A") +
  theme_minimal()

```

```{r}
var_order <- c("T_true", "C", "Y", "age", "LOS", "eGFR", "Hemoglobin", "CCI")
var_sim_ii <- c("T_true", "C", "Y")

summary_table <- function(df, name){
  if (name == "SIM_II") {
    vars_to_use <- var_sim_ii
  } else {
    vars_to_use <- var_order
  }
  
  df %>%
    select(all_of(vars_to_use)) %>%
    pivot_longer(cols = everything(),
                 names_to = "Variable",
                 values_to = "Value") %>%
    group_by(Variable) %>%
    summarise(
      Min    = round(min(Value, na.rm = TRUE), 2),
      Q1     = round(quantile(Value, 0.25, na.rm = TRUE), 2),
      Median = round(median(Value, na.rm = TRUE), 2),
      Mean   = round(mean(Value, na.rm = TRUE), 2),
      Q3     = round(quantile(Value, 0.75, na.rm = TRUE), 2),
      Max    = round(max(Value, na.rm = TRUE), 2),
      .groups = "drop"
    ) %>%
    mutate(Dataset = name) %>%
    relocate(Dataset, Variable)
}
tbl_I  <- summary_table(data_I, "SIM_I")

tbl_II <- summary_table(data_II, "SIM_II")

summary_all <- bind_rows(tbl_I, tbl_II) %>%
  mutate(Variable = factor(Variable, levels = var_order),
         Dataset  = factor(Dataset, levels = c("SIM_I", "SIM_II"))) %>%
  arrange(Dataset, Variable)  

summary_all %>%
  kable("html", booktabs = TRUE, caption = "Summary Statistics for Two Simulated Datasets") %>%
  kable_styling(latex_options = c("hold_position")) 
  # save_kable("summary_statistic.tex")
```

```{r}
censor_table <- function(df, name){
  df %>%
    mutate(censored = 1 - Delta) %>%
    summarise(
      Censor_A0 = mean(censored[A == 0], na.rm=TRUE),
      Censor_A1 = mean(censored[A == 1], na.rm=TRUE),
      Censor_Overall = mean(censored, na.rm=TRUE)
    ) %>%
    mutate(Dataset = name) %>%
    select(Dataset, everything())
}

cen_I  <- censor_table(data_I, "Data I")
cen_II <- censor_table(data_II, "Data II")

censor_all <- bind_rows(cen_I, cen_II)

censor_all %>%
  kable("html", booktabs = TRUE, digits = 3,
        caption = "Censoring Rates by Group and Overall") %>%
  kable_styling(latex_options = c("hold_position"))
  # save_kable("censoring_rate.tex")

```



```{r}
write.csv(data_I, "data/data_I.csv", row.names = FALSE)
write.csv(data_II, "data/data_II.csv", row.names = FALSE)
```



```{r}
flc <- read.csv("FISA/Data/FLChain/flchain.csv")

```

```{r}
cat("Dataset size:", nrow(flc), "\n")
cat("Columns:", names(flc), "\n")

summary(flc)

cat("\nOverall censoring rate:\n")
mean(flc$status == 0)

cat("\nCensoring rate by sex:\n")
tapply(flc$status == 0, flc$sex, mean)

ggplot(flc, aes(x = time, fill = factor(sex))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Observed Time Distribution by sex",
       x = "Observed Time (Y)",
       fill = "sex") +
  theme_minimal()

ggplot(flc, aes(x = time, fill = factor(status))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Events (Δ=1) vs Censored (Δ=0)",
       x = "Observed Time",
       fill = "Event Indicator") +
  theme_minimal()

ggplot(flc, aes(x = age, fill = factor(sex))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "Age Distribution by sex", fill = "sex") +
  theme_minimal()

flc |> filter(kappa < 10) |> 
  ggplot(aes(x = kappa, fill = factor(sex))) +
    geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
    labs(title = "< 10 kappa Distribution by sex", fill = "sex") +
    theme_minimal()

flc |> filter(lambda < 10) |> 
  ggplot(aes(x = lambda, fill = factor(sex))) +
  geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
  labs(title = "< 10 lambda Distribution by sex", fill = "sex") +
  theme_minimal()

ggplot(flc, aes(x = flc.grp, fill = factor(sex))) +
  geom_bar(alpha = 0.5, position = "identity") +
  labs(title = "flc.grp Distribution by sex", fill = "sex") +
  theme_minimal()

flc |> filter(creatinine < 4) |> 
  ggplot(aes(x = creatinine, fill = factor(sex))) +
    geom_histogram(alpha = 0.5, bins = 40, position = "identity") +
    labs(title = "< 4 creatinine Distribution by sex", fill = "sex") +
    theme_minimal()

ggplot(flc, aes(x = mgus, fill = factor(sex))) +
  geom_bar(alpha = 0.5, position = "identity") +
  labs(title = "mgus Distribution by sex", fill = "sex") +
  theme_minimal()
```












  